### ISSUE TITLE
I created a bot in synology chat, but your server report error when it received massage from it.

### ISSUE THREAD

**Issue by nizongdai** [bitcanon/synochat#3]
I use OurgoingWebhook to process the massage send by Synology Chat. 

`webhook = OutgoingWebhook(request.form, token, verbose=True)`

but it report following error.

`
Traceback (most recent call last):
  File "/home/znd/PycharmProjects/Learning/venv/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/znd/PycharmProjects/Learning/venv/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/znd/PycharmProjects/Learning/venv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/znd/PycharmProjects/Learning/venv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/znd/PycharmProjects/Learning/venv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/znd/PycharmProjects/Learning/venv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/znd/PycharmProjects/Learning/chatconnect/outChat.py", line 15, in echo
    webhook = OutgoingWebhook(request.form, token, verbose=True)
  File "/home/znd/PycharmProjects/Learning/chatconnect/synochat/webhooks.py", line 392, in __init__
    self.__channel_id 	= data['channel_id']
  File "/home/znd/PycharmProjects/Learning/venv/lib/python3.10/site-packages/werkzeug/datastructures/structures.py", line 192, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'channel_id'
`

Looks like a POST sent from a bot in Synology are different from a OutgoingWebhook massage, it does not include some information like "channel_id" and etc..

I try to print out what in the POST, showing like below.

ImmutableMultiDict([('token', 'sk8wHheSN7SABrp31ni28r3qvL6aMe6jRqPN'), ('user_id', '5'), ('username', 'nizongdai'), ('post_id', '42996917600361'), ('thread_id', '0'), ('timestamp', '1684673810360'), ('text', '111')])

only have following information.

token
user_id
username
post_id
thread_id
timestamp
text

Is that mean I need create another class like "synoBot" ? to only include these info?

**Comment by bitcanon** [comment]
The use of **bots** with Synology Chat is **not** supported (see the **Package Support** section in README.md).

I have no plans to implement bot support at the moment. The logic behind a bot seems far more complicated than a simple outgoing webhook (at a glance) and is not something I have the time or energy to look into in the near future.

But feel free to give it a go if you're up to it! 😄 

I'm closing this since it really isn't an issue, just unsupported by the library.
